version: 2
jobs:
  build:
    working_directory: ~/code
    
    docker:
      - image: circleci/python:2.7-stretch
    
    steps:
      - checkout

      - run:
          name: install virtualenv
          command: pip install virtualenv

      - run:
          name: install dependencies
          command: |
            virtualenv vision-framework
            source vision-framework/bin/activate
            pip install -r requirements.txt
        
      - run:
          name: install flake8
          command: |
            source vision-framework/bin/activate
            pip install flake8
          
      - run:
          name: Run linting
          command: |
            source vision-framework/bin/activate
            flake8 ./ --exclude=.git,__pycache__,lib,bin

      - store_artifacts:
          path: test-reports
          destination: test-reports
